version: '3.0'
services:
  webserver:
    image: docker.io/tirthankar17/dca-edureka:certprojectapp 
    ports:
      - "8080"
    networks:
      - webserver_network
    volumes:
      - appVolume:/var/log/
    deploy:
      replicas: 3
networks:
  webserver_network:
    external: true
volumes:
  appVolume:
    external: true
